apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: fastapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}

#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: {{ include "mi-app-chart.fullname" . }}
#  labels:
#    {{- include "mi-app-chart.labels" . | nindent 4 }}
#spec:
#  {{- if not .Values.autoscaling.enabled }}
#  replicas: {{ .Values.replicaCount }}
#  {{- end }}
#  selector:
#    matchLabels:
#      {{- include "mi-app-chart.selectorLabels" . | nindent 6 }}
#  template:
#    metadata:
#      {{- with .Values.podAnnotations }}
#      annotations:
#        {{- toYaml . | nindent 8 }}
#      {{- end }}
#      labels:
#        {{- include "mi-app-chart.labels" . | nindent 8 }}
#        {{- with .Values.podLabels }}
#        {{- toYaml . | nindent 8 }}
#        {{- end }}
#    spec:
#      {{- with .Values.imagePullSecrets }}
#      imagePullSecrets:
#        {{- toYaml . | nindent 8 }}
#      {{- end }}
#      serviceAccountName: {{ include "mi-app-chart.serviceAccountName" . }}
#      {{- with .Values.podSecurityContext }}
#      securityContext:
#        {{- toYaml . | nindent 8 }}
#      {{- end }}
#      containers:
#        - name: {{ .Chart.Name }}
#          {{- with .Values.securityContext }}
#          securityContext:
#            {{- toYaml . | nindent 12 }}
#          {{- end }}
#          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
#          imagePullPolicy: {{ .Values.image.pullPolicy }}
#          ports:
#            - name: http
#              containerPort: {{ .Values.service.port }}
#              protocol: TCP
#          {{- with .Values.livenessProbe }}
#          livenessProbe:
#            {{- toYaml . | nindent 12 }}
#          {{- end }}
#          {{- with .Values.readinessProbe }}
#          readinessProbe:
#            {{- toYaml . | nindent 12 }}
#          {{- end }}
#          {{- with .Values.resources }}
#          resources:
#            {{- toYaml . | nindent 12 }}
#          {{- end }}
#          {{- with .Values.volumeMounts }}
#          volumeMounts:
#            {{- toYaml . | nindent 12 }}
#          {{- end }}
#      {{- with .Values.volumes }}
#      volumes:
#        {{- toYaml . | nindent 8 }}
#      {{- end }}
#      {{- with .Values.nodeSelector }}
#      nodeSelector:
#        {{- toYaml . | nindent 8 }}
#      {{- end }}
#      {{- with .Values.affinity }}
#      affinity:
#        {{- toYaml . | nindent 8 }}
#      {{- end }}
#      {{- with .Values.tolerations }}
#      tolerations:
#        {{- toYaml . | nindent 8 }}
#      {{- end }}
#